version: '3'

services:
  kafka-produce-php-fpm:
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
    tty: true
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - kafka-network

networks:
  kafka-network:
    external: true